-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgBdKwTeQf296Kr4+M
UgwPxBMpxWSL+1b59am6yUf4om+gCgYIKoZIzj0DAQehRANCAARgu0swQbEnuyhp
cWDBoqZVAV+eG4NBuS2xm8fyWChBH1/TPMXLGKCKEROhlXCu5vcew5+bQ7YcnTlW
h02CJa8w
-----END PRIVATE KEY-----